### ISSUE TITLE
amount of timers

### ISSUE THREAD

**Issue by team-orion-777** [contrem/arduino-timer#52]
First I would like to thank you for this really easy to use and very versatile timer.

I have got a question to the amount of timers I can program. Have I got it right and the functions are limited to 16 timers? If so, is there any chance to extend this in any way, let's say 24 or 32?
As the project is growing, so is the need to control different things with the timer functions and slowly I've used all 16 ;-)

Thanks

**Comment by kpfleming** [comment]
You can define `TIMER_MAX_TASKS` before including the header file,  and set it to any value you like.

**Comment by team-orion-777** [comment]
> You can define `TIMER_MAX_TASKS` before including the header file, and set it to any value you like.

Thank you. I thought 'TIMER_MAX_TASKS (=16)'  in the manual is the limit of usable timers...

**Comment by contrem** [comment]
You can also use the *Timer* constructor to decrease/increase the number of timers

```cpp
Timer<32> timer; // Timer with 32 task slots
```
