### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by xinthose** [contrem/arduino-timer#62]
Hello.  What are the changes between the release tags?

**Comment by contrem** [comment]
You can use `git` to get that information:

`git log --oneline --no-merges  start_tag..end_tag`

Example
```
$ git log --oneline --no-merges  2.3.0..2.3.1
a90f1ff (HEAD -> master, tag: 2.3.1, origin/master) arduino-timer: 2.3.1
feefff5 src:arduino-timer:ticks use ULONG_MAX
2758496 src:arduino-timer: cpp style casts
469d15e src:arduino-timer: use task_id in cancel
```

Version numbers follow [Semantic Versioning](https://semver.org/).

**Comment by xinthose** [comment]
I would prefer an easy to read markdown file.  Thank you.
