### ISSUE TITLE
Use timerId and callbacks without argument etc.

### ISSUE THREAD

**Issue by tamtakoe** [contrem/arduino-timer#63]
1. Why do you use `Timer<>::Task timerTask` instead of `int timerId` like in JS? Id more understandable and you don't need pick in mind or looking for docs about `Timer<>::Task` instead of `auto` if variable is not defined.
2. Why you can't use just `void function_to_call()` without error or warnings? It is common way to return void and use no arguments in the callback. Boolean returning and arguments should be optional.
3. Create plz setInterval and setTimeout aliases for better compatibility with common standards.

**Comment by skrobinson** [comment]
These questions/points all seem to come from an understanding of software timers that is strongly based on JS. Other languages and frameworks have other structures and patterns that work differently, but just as well for their use cases.

**Comment by chengxg** [comment]
> 1. Why do you use `Timer<>::Task timerTask` instead of `int timerId` like in JS? Id more understandable and you don't need pick in mind or looking for docs about `Timer<>::Task` instead of `auto` if variable is not defined.
> 2. Why you can't use just `void function_to_call()` without error or warnings? It is common way to return void and use no arguments in the callback. Boolean returning and arguments should be optional.
> 3. Create plz setInterval and setTimeout aliases for better compatibility with common standards.

[https://github.com/chengxg/cxg-arduino-lib/tree/master/CxgJSTime](url)
