### ISSUE TITLE
cant pass multiple arguments

### ISSUE THREAD

**Issue by theionSami** [contrem/arduino-timer#65]
does not accept muötiple arguments
https://wokwi.com/projects/334634662909444692

**Comment by skrobinson** [comment]
Can you be more specific about what you expect and how `arduino-timer` differs from the expected behavior?

**Comment by theionSami** [comment]
can we pass a function with multiple arguments ?

**Comment by skrobinson** [comment]
No, we cannot pass a function with multiple arguments to in/at/every. But, since the single argument is a `void *`, we can make our own compound object and pass a pointer to that object.

**Comment by ali80** [comment]
I added a discussion related to this issue #66

**Comment by philj404** [comment]
See #11 for a workaround.
