### ISSUE TITLE
How long can a timer run? 

### ISSUE THREAD

**Issue by QDUNI** [contrem/arduino-timer#70]
Hi, 

How long can a timer run without needing to reset the timer/device ?

Thnx in advance

**Comment by philj404** [comment]
The timer can run indefinitely without needing a reset.  That said, if your code wants to schedule a task for over a month away, you may need to consider rollover issues.

(Internally the timer stores times as an `unsigned long`.  The next time a task should run is also an `unsigned long`.  The timer does not care what the particular value is, as it only compares the differences.  When the _difference_ between the current time and the time to run a task becomes positive, the task will run.)

You will need to consider `unsigned long` rollover issues if you want _really long_ delays (waiting over 4294967295 ticks).
That's equivalent to:

- waiting over 49 days if using the default `millis()` times (four billion milliseconds)
- waiting over 1.19 hours if using `micros()` times
